### ISSUE TITLE
截图识别无效

### ISSUE THREAD

**Issue by Seeridia** [Robert-Stackflow/CloudOTP#1]
桌面端：截图识别无效

它呼出系统截图后显示未检测到二维码，只能选择剪切板识别。

实现原理是截图后直接扫剪切板吗，那理应不会出现这样的问题

**Comment by Seeridia** [comment]
> 截图后会保存到软件目录的Screenshot文件夹下，然后识别，截图的时候都识别不了吗，如果截图面积过大的话，二维码识别效果会比较差

我目前试了好几次都不行，要不然直接截图后扫剪切板，我截图后直接用剪切板都是可以的

**Comment by Robert-Stackflow** [comment]
我再测试测试，调整下这个逻辑

**Comment by Robert-Stackflow** [comment]
已修复，见下个版本
