### ISSUE TITLE
linux 中有 libsqlcipher1 这个包

### ISSUE THREAD

**Issue by pugaizai** [Robert-Stackflow/CloudOTP#11]
linux 中有 libsqlcipher1 这个包，一定要使用tools/linux_so里面的吗？

**Comment by Robert-Stackflow** [comment]
原来有吗？我没去找，就自己拉源码编译了

**Comment by pugaizai** [comment]
> 原来有吗？我没去找，就自己拉源码编译了

我这边linux装了libsqlcipher之后启动不了
`/app/bin/cloudotp: 第 3 行：    3 段错误               （核心已转储）/app/CloudOTP/cloudotp`
