### ISSUE TITLE
about license

### ISSUE THREAD

**Issue by pugaizai** [Robert-Stackflow/CloudOTP#18]
有个问题，github 仓库里的LICENSE是GPLv3
但是官网上的服务条款

> Your use of this application is governed by the CloudOTP Privacy Policy. The Privacy Policy details how we collect, use, store and protect your information. By using this app, you agree to the terms of our Privacy Policy. 

明显和GPLv3相悖。

如果你不想别人商业化使用你的软件你可以把仓库里的LICENSE和copyright删掉。这样就算是源代码开放，但是在法律上依然是专有软件，保留解释权。或者把 Service Term 替换掉仓库里的LICENSE和copyright ，这样就声明是专有软件

**Comment by Robert-Stackflow** [comment]
服务条款是之前注册云服务开发者账号时必须的，就简单写了个，并没考虑到和仓库源代码开源协议间的联系。我之前也对开源协议没有深入了解，最近网上有一些不知名网站分发我的软件，下一步就考虑删去开源协议，感谢你的建议。

**Comment by Robert-Stackflow** [comment]
你好，综合考虑下，还是决定使用GPLv3协议，后面会修改官网上的服务条款，感谢！
