### ISSUE TITLE
UI界面的一点建议

### ISSUE THREAD

**Issue by Seeridia** [Robert-Stackflow/CloudOTP#4]
左侧功能栏上移动一点，最好是在“添加”这个元素与右边的“全部”对其
![image](https://github.com/user-attachments/assets/8e547669-31c1-408c-80a6-e7a5888740af)

**Comment by Seeridia** [comment]
> 感谢您的建议，下个版本会改下这部分UI

抱歉 试了一下，后面的那个建议——以及搜索框的左边要不加个LOGO？或是整个搜索框左移？——并不好
效果：
- 上移动一点左侧功能栏（这个可以有）
  ![image](https://github.com/user-attachments/assets/af85d418-691c-4be8-aa4c-037ebe1a9a32)
- 左移动一点左侧功能栏（这个不怎么好看）
  ![image](https://github.com/user-attachments/assets/177faaae-25e8-4b34-8c64-5c1b990ea6cc)

**Comment by Robert-Stackflow** [comment]
会在左上角加个logo，然后加号和分类对齐

**Comment by Robert-Stackflow** [comment]
已修复，见下个版本
