### ISSUE TITLE
关于"置顶"的问题

### ISSUE THREAD

**Issue by Seeridia** [Robert-Stackflow/CloudOTP#6]
- 进行置顶时，提示“取消置顶”；取消置顶时，提示“已置顶”（难道是我搞反了吗）
- 对其中一个进行置顶操作后，效果只是提前该项目，并无法移动该项目，其实并不影响其他项目移到他前面

**Comment by Robert-Stackflow** [comment]
第一个是个小bug，改一下；第二个应该是改逻辑的时候忽略了，本来是要做成置顶项目始终在前的

**Comment by Robert-Stackflow** [comment]
已修复，见下个版本
